### ISSUE TITLE
  java.lang.IllegalStateException: could not generate key in keystore

### ISSUE THREAD

**Issue by ksp147** [Crypho/cordova-plugin-secure-storage#123]
can you please help me ?
`  java.lang.IllegalStateException: could not generate key in keystore
                                                                         at android.security.AndroidKeyPairGenerator.generateKeyPair(AndroidKeyPairGenerator.java:99)
                                                                         at java.security.KeyPairGenerator$KeyPairGeneratorImpl.generateKeyPair(KeyPairGenerator.java:276)
                                                                         at com.crypho.plugins.RSA.createKeyPair(RSA.java:52)
                                                                         at com.crypho.plugins.SecureStorage$1.run(SecureStorage.java:55)
                                                                         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                         at java.lang.Thread.run(Thread.java:818)`

**Comment by demetris-manikas** [comment]
Hi, could you share some code? Also it would be great if you could describe the steps to reproduce the error.
