### ISSUE TITLE
Exception on Android Pie

### ISSUE THREAD

**Issue by BorntraegerMarc** [Crypho/cordova-plugin-secure-storage#157]
On my OnePlus 6T I always receive the following error when I `get` or `set` something:
```
W/KeyStore: KeyStore exception
    android.os.ServiceSpecificException:  (code 7)
        at android.os.Parcel.createException(Parcel.java:1964)
        at android.os.Parcel.readException(Parcel.java:1918)
        at android.os.Parcel.readException(Parcel.java:1868)
        at android.security.IKeystoreService$Stub$Proxy.get(IKeystoreService.java:786)
        at android.security.KeyStore.get(KeyStore.java:195)
        at android.security.keystore.AndroidKeyStoreSpi.engineGetCertificateChain(AndroidKeyStoreSpi.java:118)
        at java.security.KeyStoreSpi.engineGetEntry(KeyStoreSpi.java:484)
        at java.security.KeyStore.getEntry(KeyStore.java:1560)
        at com.crypho.plugins.RSA.getKeyStoreEntry(RSA.java:85)
        at com.crypho.plugins.RSA.initCipher(RSA.java:56)
        at com.crypho.plugins.RSA.decrypt(RSA.java:30)
        at com.crypho.plugins.SecureStorage$3.run(SecureStorage.java:131)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
```

The plugin still continues to work but the exception should be fixed.

I think it has something to do with an API change? Source: https://stackoverflow.com/questions/52024752/android-p-keystore-exception-android-os-servicespecificexception

PS: I'm using v3.0 of this plugin

**Comment by demetris-manikas** [comment]
I will look into it during next week.

**Comment by demetris-manikas** [comment]
I will look into it during next week.

**Comment by demetris-manikas** [comment]
@BorntraegerMarc  Thanks for reporting this.

**Comment by BorntraegerMarc** [comment]
@demetris-manikas sorry for bothering again. I'm not entirely sure what happened but the exception doesn't occur anymore on my side. Maybe it was some weird caching.

You may still verify on your side, if you want. I will get back at you if I see it again
