### ISSUE TITLE
Exception on Android Pie after adding back lock screen

### ISSUE THREAD

**Issue by BorntraegerMarc** [Crypho/cordova-plugin-secure-storage#167]
On my OnePlus 6T with Android Pie I receive the following error (see reproduction below):
```
2019-03-11 07:43:08.227 6541-6673/com.komedhealth.frontend W/KeyStore: KeyStore exception
    android.os.ServiceSpecificException:  (code 7)
        at android.os.Parcel.createException(Parcel.java:1964)
        at android.os.Parcel.readException(Parcel.java:1918)
        at android.os.Parcel.readException(Parcel.java:1868)
        at android.security.IKeystoreService$Stub$Proxy.get(IKeystoreService.java:786)
        at android.security.KeyStore.get(KeyStore.java:195)
        at android.security.keystore.AndroidKeyStoreSpi.engineGetCertificate(AndroidKeyStoreSpi.java:144)
        at java.security.KeyStore.getCertificate(KeyStore.java:1120)
        at com.crypho.plugins.RSA.loadKey(RSA.java:71)
        at com.crypho.plugins.RSA.isEntryAvailable(RSA.java:51)
        at com.crypho.plugins.SecureStorage.execute(SecureStorage.java:87)
        at org.apache.cordova.CordovaPlugin.execute(CordovaPlugin.java:117)
        at org.apache.cordova.CordovaPlugin.execute(CordovaPlugin.java:98)
        at org.apache.cordova.PluginManager.exec(PluginManager.java:132)
        at org.apache.cordova.CordovaBridge.jsExec(CordovaBridge.java:59)
        at org.apache.cordova.engine.SystemExposedJsApi.exec(SystemExposedJsApi.java:41)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:326)
        at android.os.Looper.loop(Looper.java:160)
        at android.os.HandlerThread.run(HandlerThread.java:65)
```

How to reproduce:
1. Start app with lock screen enabled (make sure you call the plugins `get` or `set` method)
1. Kill app
1. Remove lock screen
1. Re-Start app without lock screen
1. No exception happening (we handle it correctly)
1. Kill app
1. Enable lock screen again in device settings
1. Re-start app and now you see the exception

This issue is in reference to my previous issue https://github.com/Crypho/cordova-plugin-secure-storage/issues/157

Using v3.0.1 of this plugin.

**Comment by demetris-manikas** [comment]
Hi. The plugin is not supposed to function without the device having a lock screen.
It is the applications responsibility to make sure of that. 
Check [https://github.com/Crypho/cordova-plugin-secure-storage#user-content-users-must-have-a-secure-screen-lock-set](https://github.com/Crypho/cordova-plugin-secure-storage#user-content-users-must-have-a-secure-screen-lock-set) for sample implementation.

**Comment by BorntraegerMarc** [comment]
Thanks for your response @demetris-manikas

I copied the wrong reproduction steps. Please note that I'm restarting the app with the lock screen ENABLED.

Sorry I'm a bit tired this morning 😅

**Comment by demetris-manikas** [comment]
@BorntraegerMarc Could you please help a bit in resolving this since I have not much time at the moment?
Add the following code to the isEntryAvailable of the RSA.java
`catch (RuntimeException e) {
            return false;
}` and report back.

**Comment by BorntraegerMarc** [comment]
@demetris-manikas With that catch I still receive the same exception:
```
2019-03-11 08:24:55.157 16605-16720/com.komedhealth.frontend W/KeyStore: KeyStore exception
    android.os.ServiceSpecificException:  (code 7)
        at android.os.Parcel.createException(Parcel.java:1964)
        at android.os.Parcel.readException(Parcel.java:1918)
        at android.os.Parcel.readException(Parcel.java:1868)
        at android.security.IKeystoreService$Stub$Proxy.get(IKeystoreService.java:786)
        at android.security.KeyStore.get(KeyStore.java:195)
        at android.security.keystore.AndroidKeyStoreSpi.engineGetCertificate(AndroidKeyStoreSpi.java:144)
        at java.security.KeyStore.getCertificate(KeyStore.java:1120)
        at com.crypho.plugins.RSA.loadKey(RSA.java:73)
        at com.crypho.plugins.RSA.isEntryAvailable(RSA.java:51)
        at com.crypho.plugins.SecureStorage$1.run(SecureStorage.java:51)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
```

Here's the code block I changed:
```java
    public static boolean isEntryAvailable(String alias) {
        try {
            return loadKey(Cipher.ENCRYPT_MODE, alias) != null;
        } catch (RuntimeException e) {
            return false;
        } catch (Exception e) {
            return false;
        }
    }
```

**Comment by BorntraegerMarc** [comment]
But please not that the exception only happens the first time I start the app. The 2nd time it starts without the exception

**Comment by demetris-manikas** [comment]
Have you made sure that the code you changed is really being used? Since
the exception being thrown IS a RuntimeException. To be sure clone the
plugin change the code in the clone remove the plugin from your app and add
the local version of it.

Στις Δευ, 11 Μαρ 2019, 9:28 π.μ. ο χρήστης Marc Bornträger <
notifications@github.com> έγραψε:

**Comment by BorntraegerMarc** [comment]
@demetris-manikas yes I'm positive that the changed code is in effect since I changed it directly in my build project inside android studio.

But maybe it's happening because of something specific in our project...

**Comment by demetris-manikas** [comment]
The result does not make sence. Please take 5 minutes and follow the steps
i described. To be sure add a log statement as well

Στις Δευ, 11 Μαρ 2019, 10:32 π.μ. ο χρήστης Marc Bornträger <
notifications@github.com> έγραψε:

**Comment by BorntraegerMarc** [comment]
@demetris-manikas well not sure what to tell you. Here are my logs:
```
2019-03-11 11:52:38.989 9329-9557/com.komedhealth.frontend V/komed RSA: XXX before loadkey
2019-03-11 11:52:38.990 9329-9557/com.komedhealth.frontend W/KeyStore: KeyStore exception
    android.os.ServiceSpecificException:  (code 7)
        at android.os.Parcel.createException(Parcel.java:1964)
        at android.os.Parcel.readException(Parcel.java:1918)
        at android.os.Parcel.readException(Parcel.java:1868)
        at android.security.IKeystoreService$Stub$Proxy.get(IKeystoreService.java:786)
        at android.security.KeyStore.get(KeyStore.java:195)
        at android.security.keystore.AndroidKeyStoreSpi.engineGetCertificate(AndroidKeyStoreSpi.java:144)
        at java.security.KeyStore.getCertificate(KeyStore.java:1120)
        at com.crypho.plugins.RSA.loadKey(RSA.java:75)
        at com.crypho.plugins.RSA.isEntryAvailable(RSA.java:52)
        at com.crypho.plugins.SecureStorage$1.run(SecureStorage.java:51)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
2019-03-11 11:52:38.991 9329-9557/com.komedhealth.frontend W/KeyStore: KeyStore exception
    android.os.ServiceSpecificException:  (code 7)
        at android.os.Parcel.createException(Parcel.java:1964)
        at android.os.Parcel.readException(Parcel.java:1918)
        at android.os.Parcel.readException(Parcel.java:1868)
        at android.security.IKeystoreService$Stub$Proxy.get(IKeystoreService.java:786)
        at android.security.KeyStore.get(KeyStore.java:195)
        at android.security.keystore.AndroidKeyStoreSpi.engineGetCertificate(AndroidKeyStoreSpi.java:149)
        at java.security.KeyStore.getCertificate(KeyStore.java:1120)
        at com.crypho.plugins.RSA.loadKey(RSA.java:75)
        at com.crypho.plugins.RSA.isEntryAvailable(RSA.java:52)
        at com.crypho.plugins.SecureStorage$1.run(SecureStorage.java:51)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
2019-03-11 11:52:38.991 9329-9557/com.komedhealth.frontend V/komed RSA: XXX inside catch runtime exception
```

And this is my adapted method:
```java
    public static boolean isEntryAvailable(String alias) {
        try {
            Log.v("komed RSA", "XXX before loadkey");
            return loadKey(Cipher.ENCRYPT_MODE, alias) != null;
        } catch (RuntimeException e) {
            Log.v("komed RSA", "XXX inside catch runtime exception");
            return false;
        } catch (Exception e) {
            return false;
        }
    }
```

Sometimes SW dev doesn't make sense 😉

**Comment by BorntraegerMarc** [comment]
Or maybe the exception is just logged somewhere else and just printed out in the console?

**Comment by demetris-manikas** [comment]
Ok. Thanks for your efforts. I 'll try to look into it during the week

Στις Δευ, 11 Μαρ 2019, 12:54 μ.μ. ο χρήστης Marc Bornträger <
notifications@github.com> έγραψε:

**Comment by demetris-manikas** [comment]
Could be so.

Στις Δευ, 11 Μαρ 2019, 12:55 μ.μ. ο χρήστης Marc Bornträger <
notifications@github.com> έγραψε:

**Comment by BorntraegerMarc** [comment]
Cool, thanks :)

BTW, if I have a catch like this:
```java
    public static boolean isEntryAvailable(String alias) {
        try {
            return loadKey(Cipher.ENCRYPT_MODE, alias) != null;
        } catch (Exception e) {
            Log.v("komed RSA", "XXX inside catch runtime exception");
            return false;
        }
    }
```

Then I also see the exception catched log `XXX inside catch runtime exception` -> I guess because catching all exceptions also catches the runtime exception. So adding the runtime catch doesn't change the behaviour.

Maybe it was obvious for you but I'm not an experienced android dev 😄

**Comment by BorntraegerMarc** [comment]
Also I tested it now on a Samsung galaxy S9 and there the exception is not shown. So it might be a OnePlus only exception.

**Comment by demetris-manikas** [comment]
@BorntraegerMarc Just for the record catching Exception DOES NOT catch RuntimeException. See [https://docs.oracle.com/javase/tutorial/essential/exceptions/runtime.html](https://docs.oracle.com/javase/tutorial/essential/exceptions/runtime.html) for an intro.
Closing...

**Comment by demetris-manikas** [comment]
@BorntraegerMarc  Just for the record catch Exception does not catch RuntimeException. See [https://docs.oracle.com/javase/tutorial/essential/exceptions/runtime.html](https://docs.oracle.com/javase/tutorial/essential/exceptions/runtime.html).
Closing
