### ISSUE TITLE
JellyBean compatibility

### ISSUE THREAD

**Issue by tchabaud** [Crypho/cordova-plugin-secure-storage#23]
Hello,

Is this plugin compatible with Android API Level < 19 ?

Because I get the following exception : 

```
E/AndroidRuntime: FATAL EXCEPTION: pool-1-thread-2
java.lang.NoSuchMethodError: android.security.KeyPairGeneratorSpec$Builder.setKeySize
    at com.crypho.plugins.RSA.createKeyPair(RSA.java:43)
    at com.crypho.plugins.SecureStorage$1.run(SecureStorage.java:32)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
    at java.lang.Thread.run(Thread.java:841)
``` 

Is there any workaround or patches available to use this plugin on JellyBean ?

**Comment by ggozad** [comment]
No sorry, API < 19 is missing necessary cryptographic primitives that allow the plugin to work.

**Comment by tchabaud** [comment]
Ok, thanks for the info.
