### ISSUE TITLE
ss.get error 

### ISSUE THREAD

**Issue by jakeseltz** [Crypho/cordova-plugin-secure-storage#40]
Using android: when I perform a ss.get (immediately after ss.set) I get the keystore without issue. If i then close the app and open it up, then try to perform that same ss.get (having not performed a ss.remove), I recieve this error:

"nonce must have length from 7 to 13 octets"

Error: nonce must have length from 7 to 13 octets
    at fail (file:///android_asset/www/plugins/cordova-plugin-secure-storage/www/securestorage.js:59:45)
    at Object.cordova.callbackFromNative (file:///android_asset/www/cordova.js:295:52)
    at processMessage (file:///android_asset/www/cordova.js:1081:17)
    at processMessages (file:///android_asset/www/cordova.js:1104:9)
    at pollOnce (file:///android_asset/www/cordova.js:973:9)
    at pollOnceFromOnlineEvent (file:///android_asset/www/cordova.js:960:5)"

I'm having a hard time figuring out the reason for this error. If the keystore didn't exist any longer, wouldn't I receive a different error?

**Comment by ggozad** [comment]
This is for android correct? 
Would it be possible to add a failing test case?
cc @demetris-manikas

**Comment by ggozad** [comment]
Also paste some code please.

**Comment by demetris-manikas** [comment]
Are you loading stuff to the localStorage? Looks like native code tryie

**Comment by jakeseltz** [comment]
In the end it turned out that the secureStorage object was not yet loaded (even though I was calling the ss.get after the controller was loaded. That was my mistake.
