### ISSUE TITLE
App Crash on Android 4.3, Galaxy S3

### ISSUE THREAD

**Issue by AAUBSS** [Crypho/cordova-plugin-secure-storage#58]
Hi,

I encountered an app crash on a Galaxy S3. The device was secured with a pattern and in a second test run with a pin code, both runs led to this crash:

```
W/dalvikvm( 8505): threadid=34: thread exiting with uncaught exception (group=0x41c63700)
E/AndroidRuntime( 8505): FATAL EXCEPTION: pool-1-thread-2
E/AndroidRuntime( 8505): java.lang.NoSuchMethodError: android.security.KeyPairGeneratorSpec$Builder.setKeySize
E/AndroidRuntime( 8505):        at com.crypho.plugins.RSA.createKeyPair(RSA.java:43)
E/AndroidRuntime( 8505):        at com.crypho.plugins.SecureStorage$1.run(SecureStorage.java:45)
E/AndroidRuntime( 8505):        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
E/AndroidRuntime( 8505):        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
E/AndroidRuntime( 8505):        at java.lang.Thread.run(Thread.java:841)
I/ActivityManager( 2398): Notify an ApplicationCrash
I/SurfaceFlinger( 1947): id=1045 Removed NainActivit (4/5)
I/SurfaceFlinger( 1947): id=1045 Removed NainActivit (-2/5)
I/dumpstate( 8686): begin
F/libc    ( 8688): Fatal signal 13 (SIGPIPE) at 0x000021f0 (code=0), thread 8688 (uptime)
I/DEBUG   ( 1940): *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
I/DEBUG   ( 1940): Build fingerprint: 'samsung/m0xx/m0:4.3/JSS15J/I9300XXUGNA5:user/release-keys'
I/DEBUG   ( 1940): Revision: '12'
I/DEBUG   ( 1940): pid: 8688, tid: 8688, name: uptime  >>> uptime <<<
I/DEBUG   ( 1940): signal 13 (SIGPIPE), code -6 (SI_TKILL), fault addr --------
W/NativeCrashListener( 2398): Couldn't find ProcessRecord for pid 8688
I/DEBUG   ( 1940):     r0 ffffffe0  r1 404a9020  r2 00000055  r3 00000888
I/DEBUG   ( 1940):     r4 4010c170  r5 404a9020  r6 00000055  r7 00000004
I/DEBUG   ( 1940):     r8 00001000  r9 00000000  sl 4011b89c  fp 0000000c
I/DEBUG   ( 1940):     ip 4010fd8c  sp be9fd908  lr 400e42ad  pc 400df29c  cpsr 20000010
I/DEBUG   ( 1940):     d0  487adf131aef36cd  d1  0003eb7c02a108e8
I/DEBUG   ( 1940):     d2  40f18cd73aeb80a8  d3  410f5be251eb851f
I/DEBUG   ( 1940):     d4  0000000000000000  d5  0000000000000000
I/DEBUG   ( 1940):     d6  0000000000000000  d7  000118cd00000000
I/DEBUG   ( 1940):     d8  0000000000000000  d9  0000000000000000
I/DEBUG   ( 1940):     d10 0000000000000000  d11 0000000000000000
I/DEBUG   ( 1940):     d12 0000000000000000  d13 0000000000000000
I/DEBUG   ( 1940):     d14 0000000000000000  d15 0000000000000000
I/DEBUG   ( 1940):     d16 41baef36cd000000  d17 40f18cd000000000
I/DEBUG   ( 1940):     d18 41cdcd6500000000  d19 0000000000000000
I/DEBUG   ( 1940):     d20 0000000000000000  d21 0000000000000000
I/DEBUG   ( 1940):     d22 0000000000000000  d23 0000000000000000
I/DEBUG   ( 1940):     d24 0000000000000000  d25 0000000000000000
I/DEBUG   ( 1940):     d26 0000000000000000  d27 0000000000000000
I/DEBUG   ( 1940):     d28 0000000000000000  d29 0000000000000000
I/DEBUG   ( 1940):     d30 0000000000000000  d31 0000000000000000
I/DEBUG   ( 1940):     scr 00000010
I/DEBUG   ( 1940):
I/DEBUG   ( 1940): backtrace:
I/DEBUG   ( 1940):     #00  pc 0001b29c  /system/lib/libc.so (write+12)
I/DEBUG   ( 1940):     #01  pc 000202ab  /system/lib/libc.so (__sflush+54)
I/DEBUG   ( 1940):     #02  pc 00020137  /system/lib/libc.so (fclose+54)
I/DEBUG   ( 1940):     #03  pc 0000d3c5  /system/lib/libc.so
I/DEBUG   ( 1940):     #04  pc 0000e900  /system/lib/libc.so (pthread_once+108)
I/DEBUG   ( 1940):     #05  pc 0000db43  /system/lib/libc.so (malloc_debug_fini+10)
I/DEBUG   ( 1940):     #06  pc 00024639  /system/lib/libc.so (__cxa_finalize+156)
I/DEBUG   ( 1940):     #07  pc 000248f1  /system/lib/libc.so (exit+6)
I/DEBUG   ( 1940):     #08  pc 0000dc51  /system/lib/libc.so (__libc_init+52)
I/DEBUG   ( 1940):     #09  pc 000051f8  /system/bin/toolbox
I/DEBUG   ( 1940):
I/DEBUG   ( 1940): stack:
I/DEBUG   ( 1940):          be9fd8c8  00000000
I/DEBUG   ( 1940):          be9fd8cc  00000000
I/DEBUG   ( 1940):          be9fd8d0  00000000
I/DEBUG   ( 1940):          be9fd8d4  00000000
I/DEBUG   ( 1940):          be9fd8d8  00000000
I/DEBUG   ( 1940):          be9fd8dc  00000000
I/DEBUG   ( 1940):          be9fd8e0  00000000
I/DEBUG   ( 1940):          be9fd8e4  00000000
I/DEBUG   ( 1940):          be9fd8e8  61642032
I/DEBUG   ( 1940):          be9fd8ec  202c7379
I/DEBUG   ( 1940):          be9fd8f0  353a3730
I/DEBUG   ( 1940):          be9fd8f4  35313a36
I/DEBUG   ( 1940):          be9fd8f8  4010c170  /system/lib/libc.so
I/DEBUG   ( 1940):          be9fd8fc  404a9020  [heap]
I/DEBUG   ( 1940):          be9fd900  df0027ad
I/DEBUG   ( 1940):          be9fd904  00000000
I/DEBUG   ( 1940):     #00  be9fd908  4010c170  /system/lib/libc.so
I/DEBUG   ( 1940):          ........  ........
I/DEBUG   ( 1940):     #01  be9fd908  4010c170  /system/lib/libc.so
I/DEBUG   ( 1940):          be9fd90c  00000008
I/DEBUG   ( 1940):          be9fd910  4010fd8c
I/DEBUG   ( 1940):          be9fd914  400e413b  /system/lib/libc.so (fclose+58)
I/DEBUG   ( 1940):     #02  be9fd918  4010c11c  /system/lib/libc.so
I/DEBUG   ( 1940):          be9fd91c  400d13b1  /system/lib/libc.so
I/DEBUG   ( 1940):          be9fd920  00000000
I/DEBUG   ( 1940):          be9fd924  400d13c9  /system/lib/libc.so
I/DEBUG   ( 1940):
I/DEBUG   ( 1940): memory near r1:
I/DEBUG   ( 1940):     404a9000 00000000 0000001b 4010c064 4010c064
I/DEBUG   ( 1940):     404a9010 400d29e9 400d34a1 400d29f9 0000100b
I/DEBUG   ( 1940):     404a9020 74207075 3a656d69 64203320 2c737961
I/DEBUG   ( 1940):     404a9030 3a333020 323a3435 69202c31 20656c64
I/DEBUG   ( 1940):     404a9040 656d6974 2032203a 73796164 3332202c
I/DEBUG   ( 1940):     404a9050 3a31323a 202c3233 65656c73 69742070
I/DEBUG   ( 1940):     404a9060 203a656d 61642032 202c7379 353a3730
I/DEBUG   ( 1940):     404a9070 35313a36 73696d0a 6f6e0a63 09766564
I/DEBUG   ( 1940):     404a9080 75626564 0a736667 65646f6e 6f730976
I/DEBUG   ( 1940):     404a9090 73666b63 646f6e0a 75097665 73666273
I/DEBUG   ( 1940):     404a90a0 646f6e0a 70097665 66657069 6f6e0a73
I/DEBUG   ( 1940):     404a90b0 09766564 6e6f6e61 6f6e695f 73666564
I/DEBUG   ( 1940):     404a90c0 646f6e0a 64097665 74707665 65090a73
I/DEBUG   ( 1940):     404a90d0 0a327478 74786509 65090a33 0a347478
I/DEBUG   ( 1940):     404a90e0 65646f6e 61720976 0a73666d 61667609
I/DEBUG   ( 1940):     404a90f0 6d090a74 736f6473 646f6e0a 65097665
I/DEBUG   ( 1940):
I/DEBUG   ( 1940): memory near r4:
I/DEBUG   ( 1940):     4010c150 00000000 00000000 00000000 00000000
I/DEBUG   ( 1940):     4010c160 00000000 00000000 00000000 00000000
I/DEBUG   ( 1940):     4010c170 404a9020 00000000 00001000 00010888
I/DEBUG   ( 1940):     4010c180 404a9020 00001000 00000000 4010c170
I/DEBUG   ( 1940):     4010c190 400e5e5f 400e5de1 400e5e3b 400e5e03
I/DEBUG   ( 1940):     4010c1a0 4010c23c 00000000 00000000 00000000
I/DEBUG   ( 1940):     4010c1b0 00000000 00000000 00000000 00001000
I/DEBUG   ( 1940):     4010c1c0 00000000 00000000 00000000 00000000
I/DEBUG   ( 1940):     4010c1d0 0002000a 00000000 00000000 00000000
I/DEBUG   ( 1940):     4010c1e0 4010c1c4 400e5e5f 400e5de1 400e5e3b
I/DEBUG   ( 1940):     4010c1f0 400e5e03 4010c24c 00000000 00000000
I/DEBUG   ( 1940):     4010c200 00000000 00000000 00000000 00000000
I/DEBUG   ( 1940):     4010c210 00000000 00000000 00000000 ffffffff
I/DEBUG   ( 1940):     4010c220 00000000 00000011 4010f39c 00000000
I/DEBUG   ( 1940):     4010c230 00000000 00000000 00004000 00000000
I/DEBUG   ( 1940):     4010c240 00000000 00000000 00004000 00000000
I/DEBUG   ( 1940):
I/DEBUG   ( 1940): memory near r5:
I/DEBUG   ( 1940):     404a9000 00000000 0000001b 4010c064 4010c064
I/DEBUG   ( 1940):     404a9010 400d29e9 400d34a1 400d29f9 0000100b
I/DEBUG   ( 1940):     404a9020 74207075 3a656d69 64203320 2c737961
I/DEBUG   ( 1940):     404a9030 3a333020 323a3435 69202c31 20656c64
I/DEBUG   ( 1940):     404a9040 656d6974 2032203a 73796164 3332202c
I/DEBUG   ( 1940):     404a9050 3a31323a 202c3233 65656c73 69742070
I/DEBUG   ( 1940):     404a9060 203a656d 61642032 202c7379 353a3730
I/DEBUG   ( 1940):     404a9070 35313a36 73696d0a 6f6e0a63 09766564
I/DEBUG   ( 1940):     404a9080 75626564 0a736667 65646f6e 6f730976
I/DEBUG   ( 1940):     404a9090 73666b63 646f6e0a 75097665 73666273
I/DEBUG   ( 1940):     404a90a0 646f6e0a 70097665 66657069 6f6e0a73
I/DEBUG   ( 1940):     404a90b0 09766564 6e6f6e61 6f6e695f 73666564
I/DEBUG   ( 1940):     404a90c0 646f6e0a 64097665 74707665 65090a73
I/DEBUG   ( 1940):     404a90d0 0a327478 74786509 65090a33 0a347478
I/DEBUG   ( 1940):     404a90e0 65646f6e 61720976 0a73666d 61667609
I/DEBUG   ( 1940):     404a90f0 6d090a74 736f6473 646f6e0a 65097665
I/DEBUG   ( 1940):
I/DEBUG   ( 1940): memory near r8:
I/DEBUG   ( 1940):     00000fe0 ffffffff ffffffff ffffffff ffffffff
I/DEBUG   ( 1940):     00000ff0 ffffffff ffffffff ffffffff ffffffff
I/DEBUG   ( 1940):     00001000 ffffffff ffffffff ffffffff ffffffff
I/DEBUG   ( 1940):     00001010 ffffffff ffffffff ffffffff ffffffff
I/DEBUG   ( 1940):     00001020 ffffffff ffffffff ffffffff ffffffff
I/DEBUG   ( 1940):     00001030 ffffffff ffffffff ffffffff ffffffff
I/DEBUG   ( 1940):     00001040 ffffffff ffffffff ffffffff ffffffff
I/DEBUG   ( 1940):     00001050 ffffffff ffffffff ffffffff ffffffff
I/DEBUG   ( 1940):     00001060 ffffffff ffffffff ffffffff ffffffff
I/DEBUG   ( 1940):     00001070 ffffffff ffffffff ffffffff ffffffff
I/DEBUG   ( 1940):     00001080 ffffffff ffffffff ffffffff ffffffff
I/DEBUG   ( 1940):     00001090 ffffffff ffffffff ffffffff ffffffff
I/DEBUG   ( 1940):     000010a0 ffffffff ffffffff ffffffff ffffffff
I/DEBUG   ( 1940):     000010b0 ffffffff ffffffff ffffffff ffffffff
I/DEBUG   ( 1940):     000010c0 ffffffff ffffffff ffffffff ffffffff
I/DEBUG   ( 1940):     000010d0 ffffffff ffffffff ffffffff ffffffff
I/DEBUG   ( 1940):
I/DEBUG   ( 1940): memory near sl:
I/DEBUG   ( 1940):     4011b87c 00000000 00000000 00000000 00000000
I/DEBUG   ( 1940):     4011b88c 00000000 00000000 00000000 00000000
I/DEBUG   ( 1940):     4011b89c 4006a000 00000001 00000000 00000000
I/DEBUG   ( 1940):     4011b8ac 00000000 00000000 00000000 00000000
I/DEBUG   ( 1940):     4011b8bc 00000000 00000000 00000000 00000000
I/DEBUG   ( 1940):     4011b8cc 00000000 00000000 00000000 00000000
I/DEBUG   ( 1940):     4011b8dc 00000000 00000000 00000000 00000000
I/DEBUG   ( 1940):     4011b8ec 00000000 00000000 00000000 00000000
I/DEBUG   ( 1940):     4011b8fc 00000000 00000000 00000000 00000000
I/DEBUG   ( 1940):     4011b90c 00000000 00000000 00000000 00000000
I/DEBUG   ( 1940):     4011b91c 00000000 00000000 00000000 00000000
I/DEBUG   ( 1940):     4011b92c 00000000 00000000 00000000 00000000
I/DEBUG   ( 1940):     4011b93c 00000000 00000000 00000000 00000000
I/DEBUG   ( 1940):     4011b94c 00000000 00000000 00000000 00000000
I/DEBUG   ( 1940):     4011b95c 00000000 00000000 00000000 00000000
I/DEBUG   ( 1940):     4011b96c 00000000 00000000 00000000 00000000
I/DEBUG   ( 1940):
I/DEBUG   ( 1940): memory near ip:
I/DEBUG   ( 1940):     4010fd6c 00000000 00000000 00000000 00000000
I/DEBUG   ( 1940):     4010fd7c 00000000 00000000 00000000 00000001
I/DEBUG   ( 1940):     4010fd8c 00000000 00000000 00000000 00000000
I/DEBUG   ( 1940):     4010fd9c 00000000 00000000 00000000 00000000
I/DEBUG   ( 1940):     4010fdac 00000000 00000000 00000000 00000000
I/DEBUG   ( 1940):     4010fdbc 00000000 00000000 00000000 00000000
I/DEBUG   ( 1940):     4010fdcc 00000000 00000000 00000000 00000000
I/DEBUG   ( 1940):     4010fddc 00000000 00000000 00000000 00000000
I/DEBUG   ( 1940):     4010fdec 00000000 00000000 00000000 00000000
I/DEBUG   ( 1940):     4010fdfc 00000000 00000000 00000000 00000000
I/DEBUG   ( 1940):     4010fe0c 00000000 00000000 00000000 00000000
I/DEBUG   ( 1940):     4010fe1c 00000000 00000000 00000000 00000000
I/DEBUG   ( 1940):     4010fe2c 00000000 00000000 00000000 00000000
I/DEBUG   ( 1940):     4010fe3c 00000000 00000000 00000000 00000000
I/DEBUG   ( 1940):     4010fe4c 00000000 00000000 00000000 00000000
I/DEBUG   ( 1940):     4010fe5c 00000000 00000000 00000000 00000000
I/DEBUG   ( 1940):
I/DEBUG   ( 1940): memory near sp:
I/DEBUG   ( 1940):     be9fd8e8 61642032 202c7379 353a3730 35313a36
I/DEBUG   ( 1940):     be9fd8f8 4010c170 404a9020 df0027ad 00000000
I/DEBUG   ( 1940):     be9fd908 4010c170 00000008 4010fd8c 400e413b
I/DEBUG   ( 1940):     be9fd918 4010c11c 400d13b1 00000000 400d13c9
I/DEBUG   ( 1940):     be9fd928 4010ebe8 400d2904 4006a000 4006a018
I/DEBUG   ( 1940):     be9fd938 00000001 400d1b47 00000000 400e863b
I/DEBUG   ( 1940):     be9fd948 000000d5 4006a024 00000000 400d5b41
I/DEBUG   ( 1940):     be9fd958 4006b7c4 00000000 00000031 00000000
I/DEBUG   ( 1940):     be9fd968 be9fd9cc 00000001 4010bfd8 40051345
I/DEBUG   ( 1940):     be9fd978 00000000 00000000 be9fd9bc 400e88f5
I/DEBUG   ( 1940):     be9fd988 00000000 400d1c55 00000000 00000000
I/DEBUG   ( 1940):     be9fd998 00000000 00000000 00000000 400511fc
I/DEBUG   ( 1940):     be9fd9a8 4006b7b4 4006b7bc 4006b7c4 be9fd9c0
I/DEBUG   ( 1940):     be9fd9b8 00000000 400b3849 00000001 be9fdac1
I/DEBUG   ( 1940):     be9fd9c8 00000000 be9fdac8 be9fdb05 be9fdb2d
I/DEBUG   ( 1940):     be9fd9d8 be9fdb40 be9fdb55 be9fdb70 be9fdb83
I/DEBUG   ( 1940):
I/DEBUG   ( 1940): code around pc:
I/DEBUG   ( 1940):     400df27c e1a0700c e3700a01 912fff1e e2600000
I/DEBUG   ( 1940):     400df28c ea008358 e1a0c007 e3a07004 ef000000
I/DEBUG   ( 1940):     400df29c e1a0700c e3700a01 912fff1e e2600000
I/DEBUG   ( 1940):     400df2ac ea008350 e1a0c00d e92d00f0 e89c0070
I/DEBUG   ( 1940):     400df2bc e3a070b4 ef000000 e8bd00f0 e3700a01
I/DEBUG   ( 1940):     400df2cc 912fff1e e2600000 ea008346 e1a0c00d
I/DEBUG   ( 1940):     400df2dc e92d00f0 e89c0070 e3a070b5 ef000000
I/DEBUG   ( 1940):     400df2ec e8bd00f0 e3700a01 912fff1e e2600000
I/DEBUG   ( 1940):     400df2fc ea00833c e1a0c007 e3a07005 ef000000
I/DEBUG   ( 1940):     400df30c e1a0700c e3700a01 912fff1e e2600000
I/DEBUG   ( 1940):     400df31c ea008334 e1a0c007 e59f7014 ef000000
I/DEBUG   ( 1940):     400df32c e1a0700c e3700a01 912fff1e e2600000
I/DEBUG   ( 1940):     400df33c ea00832c 00000142 e1a0c007 e3a07006
I/DEBUG   ( 1940):     400df34c ef000000 e1a0700c e3700a01 912fff1e
I/DEBUG   ( 1940):     400df35c e2600000 ea008323 e1a0c007 e3a07013
I/DEBUG   ( 1940):     400df36c ef000000 e1a0700c e3700a01 912fff1e
I/DEBUG   ( 1940):
I/DEBUG   ( 1940): code around lr:
I/DEBUG   ( 1940):     400e428c 68260799 bf086025 ebc56961 bf180606
I/DEBUG   ( 1940):     400e429c 60a12100 6ae3e00f 69e04629 47984632
I/DEBUG   ( 1940):     400e42ac dc062800 f04289a2 81a00040 30fff04f
I/DEBUG   ( 1940):     400e42bc 1a36bd70 2e00182d e7dcdced 4a0b4b0a
I/DEBUG   ( 1940):     400e42cc b570447b 589b4604 461d6819 f00ab109
I/DEBUG   ( 1940):     400e42dc 4620fd82 ffc8f7ff 68284606 4620b110
I/DEBUG   ( 1940):     400e42ec fd86f00a bd704630 00027d08 ffffff60
I/DEBUG   ( 1940):     400e42fc b5704b13 4604447b 4812b928 e8bd4478
I/DEBUG   ( 1940):     400e430c f0004070 4a10bfe5 6819589b b109461e
I/DEBUG   ( 1940):     400e431c fd61f00a f00089a0 b9350518 fe08f7f3
I/DEBUG   ( 1940):     400e432c 35fff04f 60022209 4620e003 ff9cf7ff
I/DEBUG   ( 1940):     400e433c 68334605 4620b113 fd5af00a bd704628
I/DEBUG   ( 1940):     400e434c 00027cd4 ffffffbd ffffff60 46034a0a
I/DEBUG   ( 1940):     400e435c 447a490a 68115852 6842b959 60411e51
I/DEBUG   ( 1940):     400e436c da012900 bbcef001 f8126802 601a0b01
I/DEBUG   ( 1940):     400e437c f0014770 bf00b811 00027c76 ffffff60
I/DEBUG   ( 1940): !@dumpstate -k -t -z -d -o /data/log/dumpstate_app_native -m 8688
```

**Comment by ggozad** [comment]
Which android version is the device running?

**Comment by AAUBSS** [comment]
It's running android 4.3.

**Comment by ggozad** [comment]
Well, that's your problem. We need API 19, which is available from 4.4.

**Comment by AAUBSS** [comment]
In that case you should consider adding the required api version in your plugin.xml

```
<preference name="android-minSdkVersion" default="19" />
```

**Comment by ggozad** [comment]
You are right of course. We actually had it in plugin.xml. If my memory does not deceive me it caused some problems with either ionic or phonegap, which is why we removed it and added the info in the README. Once I have the time I will dig the issue and see if it is still a problem, otherwise put it back.

**Comment by AAUBSS** [comment]
Is there a possibility of a graceful fallback for those devices? Can you save data unsecured in those cases and/or inform the app about not being able to save data secure with the option of letting it handle the data saving in an alternative storage?

**Comment by ggozad** [comment]
Problem is the android part of the plugin has already become overly complex in order to support the various variants. We now support two versions of AES, one native and one done through js depending on whether we are on >21 or not. This is because there is no keychain/vault built-in.

Eventually I would like to even drop support for android < 21, but that's not going to happen very soon.

You could in principle add a third compatibility layer where public/private key encryption happens with sjcl through elliptic curves. But that would be a nightmare to manage I am afraid.

I would suggest the following:
During initialisation detect whether we are on android > 21 and fail gracefully if not. There are already checks there to see whether there is a lock pattern etc on the device which is the other way init should fail. If initialisation fails the app could decide whether to inform the user that his data will not be secure or implement some other method.

**Comment by AAUBSS** [comment]
Thank you for your detailed answer!

**Comment by ggozad** [comment]
A pleasure.
