### ISSUE TITLE
NoSuchMethod

### ISSUE THREAD

**Issue by hellish** [Crypho/cordova-plugin-secure-storage#84]
Hello, I installed Secure storage but i get an error in playstore's crash report for 
Android 4.2.

```
java.lang.NoSuchMethodError: javax.crypto.Cipher.updateAAD
	at com.crypho.plugins.AES.initCipher(AES.java:72)
	at com.crypho.plugins.AES.encrypt(AES.java:29)
	at com.crypho.plugins.SecureStorage$2.run(SecureStorage.java:101)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
	at java.lang.Thread.run(Thread.java:856)
```

**Comment by demetris-manikas** [comment]
Maybe this should be more visible in the docs. Android needs API 19 and higher. Android 4.2 is API 17. 
@ggozad Maybe add Android 4.4 KitKat next to API 19.

Cheers.

**Comment by ggozad** [comment]
Thanks @demetris-manikas clarification added.
