### ISSUE TITLE
Error input must be under 256 bytes. Android 4.4.2

### ISSUE THREAD

**Issue by Remicek** [Crypho/cordova-plugin-secure-storage#96]
Hey, in the app i develope we have two routes:
1) User have pin/pattern enabled - everything fine
2) User doesnt have the pin and its asked to set it up, afer setting the pin we restart the app.

I use version 2.6.3 (the newest available now).
ss.secureDevice method return success. So secure storage should be ready.

Now in the second case we get this error, when trying to set key-value pair (it doesn't happen on android 6.0):

> input must be under 256 bytes

(No i don't have any key-values bigger than this at most i am storing 64bits string.)

```
03-16 19:06:43.112: E/SecureStorage(28830): Decrypt (RSA) failed :
03-16 19:06:43.112: E/SecureStorage(28830): javax.crypto.IllegalBlockSizeException: input must be under 256 bytes
03-16 19:06:43.112: E/SecureStorage(28830):  at com.android.org.conscrypt.OpenSSLCipherRSA.engineDoFinal(OpenSSLCipherRSA.java:245)
03-16 19:06:43.112: E/SecureStorage(28830):  at javax.crypto.Cipher.doFinal(Cipher.java:1204)
03-16 19:06:43.112: E/SecureStorage(28830):  at com.crypho.plugins.RSA.decrypt(RSA.java:31)
03-16 19:06:43.112: E/SecureStorage(28830):  at com.crypho.plugins.SecureStorage$4.run(SecureStorage.java:150)
03-16 19:06:43.112: E/SecureStorage(28830):  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
03-16 19:06:43.112: E/SecureStorage(28830):  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
03-16 19:06:43.112: E/SecureStorage(28830):  at java.lang.Thread.run(Thread.java:848)
03-16 19:06:43.126: E/SecureStorage(28830): Decrypt (RSA) failed :
03-16 19:06:43.126: E/SecureStorage(28830): javax.crypto.IllegalBlockSizeException: input must be under 256 bytes
03-16 19:06:43.126: E/SecureStorage(28830):  at com.android.org.conscrypt.OpenSSLCipherRSA.engineDoFinal(OpenSSLCipherRSA.java:245)
03-16 19:06:43.126: E/SecureStorage(28830):  at javax.crypto.Cipher.doFinal(Cipher.java:1204)
03-16 19:06:43.126: E/SecureStorage(28830):  at com.crypho.plugins.RSA.decrypt(RSA.java:31)
03-16 19:06:43.126: E/SecureStorage(28830):  at com.crypho.plugins.SecureStorage$4.run(SecureStorage.java:150)
03-16 19:06:43.126: E/SecureStorage(28830):  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
03-16 19:06:43.126: E/SecureStorage(28830):  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
03-16 19:06:43.126: E/SecureStorage(28830):  at java.lang.Thread.run(Thread.java:848)
03-16 19:06:44.617: E/SecureStorage(28830): Encrypt (RSA) failed :
03-16 19:06:44.617: E/SecureStorage(28830): javax.crypto.IllegalBlockSizeException: input must be under 256 bytes
03-16 19:06:44.617: E/SecureStorage(28830):  at com.android.org.conscrypt.OpenSSLCipherRSA.engineDoFinal(OpenSSLCipherRSA.java:245)
03-16 19:06:44.617: E/SecureStorage(28830):  at javax.crypto.Cipher.doFinal(Cipher.java:1204)
03-16 19:06:44.617: E/SecureStorage(28830):  at com.crypho.plugins.RSA.encrypt(RSA.java:24)
03-16 19:06:44.617: E/SecureStorage(28830):  at com.crypho.plugins.SecureStorage$5.run(SecureStorage.java:165)
03-16 19:06:44.617: E/SecureStorage(28830):  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
03-16 19:06:44.617: E/SecureStorage(28830):  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
03-16 19:06:44.617: E/SecureStorage(28830):  at java.lang.Thread.run(Thread.java:848)
03-16 19:06:44.633: E/SecureStorage(28830): Encrypt (RSA) failed :
03-16 19:06:44.633: E/SecureStorage(28830): javax.crypto.IllegalBlockSizeException: input must be under 256 bytes
03-16 19:06:44.633: E/SecureStorage(28830):  at com.android.org.conscrypt.OpenSSLCipherRSA.engineDoFinal(OpenSSLCipherRSA.java:245)
03-16 19:06:44.633: E/SecureStorage(28830):  at javax.crypto.Cipher.doFinal(Cipher.java:1204)
03-16 19:06:44.633: E/SecureStorage(28830):  at com.crypho.plugins.RSA.encrypt(RSA.java:24)
03-16 19:06:44.633: E/SecureStorage(28830):  at com.crypho.plugins.SecureStorage$5.run(SecureStorage.java:165)
03-16 19:06:44.633: E/SecureStorage(28830):  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
03-16 19:06:44.633: E/SecureStorage(28830):  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
03-16 19:06:44.633: E/SecureStorage(28830):  at java.lang.Thread.run(Thread.java:848)
```

My guess is that something must be wrong with setting AES key (its too long?)

   ```
_sjcl_set: function (success, error, key, value) {
        var AESKey, encValue;

        AESKey = sjcl_ss.random.randomWords(8);
        _AES_PARAM.adata = this.service;
        encValue = sjcl_ss.encrypt(AESKey, value, _AES_PARAM);

        // Encrypt the AES key
        _executeNativeMethod(
            function (encKey) {
                _executeNativeMethod(
                    function () {
                        success(key);
                    },
                    error,
                    'store',
                    ['_SS_' + key, JSON.stringify({key: encKey, value: encValue})]
                );
            },
            error,
            'encrypt_rsa',
            [sjcl_ss.codec.base64.fromBits(AESKey)]
        );
    },
```

**Comment by ggozad** [comment]
Yes the key is longer than the RSA key which should not be the case on API 19. Could you please run the tests and let me know what the result is?

**Comment by Remicek** [comment]
@ggozad 
Steps taken
1) Disable pin
2) Run manual test (init storage)
3) Set pin
4) Go back run automatic tests.

Here are the results of auto tests.
![autotestencryptedlocalstorage](https://cloud.githubusercontent.com/assets/4086702/24053294/e05d8056-0b38-11e7-80ff-95d6fac73c3e.png)

**Comment by demetris-manikas** [comment]
@ggozad Test fixed in PR but this is irrelevant to this issue.
@Remicek The storage is ready to use when the initialization success callback is called and 
not when the secureDevice succeeds. 
Can you share a bit of code? It would be easier for us to trace the error.

**Comment by Remicek** [comment]
@demetris-manikas after all it was a problem with my code, not with plugin itself. 
Thanks for help

**Comment by demetris-manikas** [comment]
@Remicek The code and the log don't match... Can you please provide matching ones?
Also this reminds me of the forgetful keystore mentioned in the README. Can you please attach the relevant log from the device?

**Comment by Remicek** [comment]
@demetris-manikas 

So there are 3 parts in that log (i've pasted only the 2nd and 3rd one, sorry about that)..
1) User has set pin: and run app::
```
Received Event: deviceready index.js:25
Encrypted local storage available on first try index.js:32
testGetFromLocalStorage index.js:57
testSaveToLocalStorageFirst index.js:65
Error testGetFromLocalStorage Error: Key [_SS_myFirstKey] not found. index.js:60
Set myFirstKey index.js:67
```

2) User removed the pin and run app:

```
Received Event: deviceready index.js:25
Pattern was set index.js:42
Encrypted local storage available on first try index.js:32
testGetFromLocalStorage index.js:57
testSaveToLocalStorageFirst index.js:65
Error testGetFromLocalStorage Error: error:0407106B:rsa routines:RSA_padding_check_PKCS1_type_2:block type is not 02 index.js:60
Set myFirstKey index.js:67
```

3) I try to set another key using the method below:

```
 ss.set(
                    function (key) {
                        console.log('setKeyPairToLocalStorageNew key: ' + key + " and value " + value);
                    },
                    function (error) {
                        console.log('Error ' + error);
                     },
                    'TestSecondKey', 'secindKeyvalue');
```

i get:
```

undefined
Error Error: input must be under 256 bytes
```

**Comment by demetris-manikas** [comment]
@Remicek Reproduced. I am on it. I 'll let you know of my findings. Thanks.

**Comment by demetris-manikas** [comment]
@Remicek I believe I got it. Please check if #104 resolves the issue for you too.

**Comment by Remicek** [comment]
@demetris-manikas 
Works like a charm now, thanks :)

**Comment by demetris-manikas** [comment]
The changes are not merged yet so I keep this open
